import { Account, Video, TrendData } from '@/types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    username: 'almaty_toys',
    displayName: 'Алматы Ойыншықтары',
    platform: 'instagram',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Балаларға арналған ең жақсы ойыншықтар 🧸 Алматыда жеткізу бар',
    followers: 45200,
    following: 230,
    totalVideos: 127,
    totalViews: 892000,
    totalLikes: 124500,
    totalComments: 3400,
    avgViews: 7023,
    avgLikes: 980,
    engagementRate: 4.2,
    lastPostDate: '2024-09-28',
    isVerified: false,
    region: 'almaty',
    regionVerified: true,
    source: 'Instagram Official API (demo)',
    lastUpdated: new Date().toISOString(),
    isDemo: true
  },
  {
    id: '2',
    username: 'toy_world_kz',
    displayName: 'Toy World Kazakhstan',
    platform: 'tiktok',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Ойыншықтарға шолу, распаковка 🎁',
    followers: 128000,
    totalVideos: 342,
    totalViews: 3420000,
    totalLikes: 567000,
    totalComments: 12300,
    avgViews: 10000,
    avgLikes: 1657,
    engagementRate: 5.8,
    lastPostDate: '2024-09-29',
    region: 'kazakhstan',
    regionVerified: false,
    source: 'TikTok Official API (demo)',
    lastUpdated: new Date().toISOString(),
    isDemo: true
  },
  {
    id: '3',
    username: 'balalar_alemi',
    displayName: 'Балалар Әлемі',
    platform: 'instagram',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Балалар тауарлары дүкені',
    followers: 23100,
    totalVideos: 89,
    totalViews: 445000,
    totalLikes: 45200,
    totalComments: 1200,
    avgViews: 5000,
    avgLikes: 507,
    engagementRate: 3.1,
    lastPostDate: '2024-09-25',
    region: 'astana',
    regionVerified: true,
    source: 'Instagram Official API (demo)',
    lastUpdated: new Date().toISOString(),
    isDemo: true
  },
  {
    id: '4',
    username: 'coffee_almaty',
    displayName: 'Coffee Almaty ☕',
    platform: 'instagram',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Алматыдағы ең дәмді кофе',
    followers: 89200,
    totalVideos: 210,
    totalViews: 1200000,
    totalLikes: 234000,
    totalComments: 5600,
    avgViews: 5714,
    avgLikes: 1114,
    engagementRate: 6.2,
    lastPostDate: '2024-09-30',
    region: 'almaty',
    regionVerified: true,
    source: 'Instagram Official API (demo)',
    lastUpdated: new Date().toISOString(),
    isDemo: true
  },
  {
    id: '5',
    username: 'beauty_kz',
    displayName: 'Beauty Kazakhstan',
    platform: 'tiktok',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Косметика, уход, обзоры',
    followers: 201000,
    totalVideos: 523,
    totalViews: 8900000,
    totalLikes: 1200000,
    totalComments: 34000,
    avgViews: 17017,
    avgLikes: 2294,
    engagementRate: 7.1,
    lastPostDate: '2024-09-30',
    region: 'kazakhstan',
    regionVerified: false,
    source: 'TikTok Official API (demo)',
    lastUpdated: new Date().toISOString(),
    isDemo: true
  }
]

export const mockVideos: Video[] = [
  {
    id: 'v1',
    accountId: '1',
    platform: 'instagram',
    thumbnail: 'https://picsum.photos/seed/v1/400/400',
    title: 'Жаңа LEGO жинағы келді!',
    caption: 'Балаңызға арналған ең керемет LEGO! 🎉 #ойыншық #almaty #балалар #lego #игрушки',
    url: 'https://instagram.com/p/demo1',
    publishedAt: '2024-09-28',
    views: 12300,
    likes: 890,
    comments: 45,
    shares: 12,
    engagementRate: 7.7,
    hashtags: ['ойыншық', 'almaty', 'балалар', 'lego'],
    contentType: 'product_showcase',
    isDemo: true
  },
  {
    id: 'v2',
    accountId: '2',
    platform: 'tiktok',
    thumbnail: 'https://picsum.photos/seed/v2/400/700',
    title: 'Ойыншық распаковка',
    caption: 'Бүгінгі распаковка 😍 Мына ойыншық хит болып жатыр! #распаковка #ойыншық #тренд',
    url: 'https://tiktok.com/@toy_world_kz/video/demo2',
    publishedAt: '2024-09-29',
    views: 45200,
    likes: 3200,
    comments: 123,
    shares: 234,
    engagementRate: 7.8,
    hashtags: ['распаковка', 'ойыншық', 'тренд'],
    contentType: 'unboxing',
    isDemo: true
  },
  {
    id: 'v3',
    accountId: '1',
    platform: 'instagram',
    thumbnail: 'https://picsum.photos/seed/v3/400/400',
    title: 'Балалар ойыншықтары -30%',
    caption: 'Тек бүгін -30% жеңілдік! 🛒 #жеңілдік #ойыншық #almaty',
    url: 'https://instagram.com/p/demo3',
    publishedAt: '2024-09-27',
    views: 8900,
    likes: 450,
    comments: 23,
    engagementRate: 5.3,
    hashtags: ['жеңілдік', 'ойыншық'],
    contentType: 'promo',
    isDemo: true
  },
  {
    id: 'v4',
    accountId: '4',
    platform: 'instagram',
    thumbnail: 'https://picsum.photos/seed/v4/400/400',
    title: 'Latte art',
    caption: 'Бүгінгі латте арт ☕ #coffee #almaty #кофе',
    url: 'https://instagram.com/p/demo4',
    publishedAt: '2024-09-30',
    views: 15600,
    likes: 2100,
    comments: 89,
    engagementRate: 14.0,
    hashtags: ['coffee', 'almaty', 'кофе'],
    contentType: 'lifestyle',
    isDemo: true
  },
  {
    id: 'v5',
    accountId: '5',
    platform: 'tiktok',
    thumbnail: 'https://picsum.photos/seed/v5/400/700',
    title: 'Косметика обзор',
    caption: 'Бұл крем шынымен жұмыс істей ме? Тест! #косметика #обзор #beauty',
    url: 'https://tiktok.com/@beauty_kz/video/demo5',
    publishedAt: '2024-09-29',
    views: 89200,
    likes: 7800,
    comments: 342,
    shares: 123,
    engagementRate: 9.2,
    hashtags: ['косметика', 'обзор', 'beauty'],
    contentType: 'review',
    isDemo: true
  }
]

export const mockTrendData: TrendData = {
  niche: 'ойыншық',
  accounts: mockAccounts.slice(0, 3),
  topVideos: mockVideos.slice(0, 3),
  hashtags: [
    { tag: 'ойыншық', count: 342 },
    { tag: 'балалар', count: 231 },
    { tag: 'almaty', count: 189 },
    { tag: 'игрушки', count: 156 },
    { tag: 'распаковка', count: 98 },
  ],
  commonWords: [
    { word: 'балалар', count: 89 },
    { word: 'ойыншық', count: 76 },
    { word: 'жаңа', count: 45 },
    { word: 'келді', count: 34 },
  ],
  postingFrequency: [
    { date: '2024-09-24', count: 3 },
    { date: '2024-09-25', count: 5 },
    { date: '2024-09-26', count: 2 },
    { date: '2024-09-27', count: 7 },
    { date: '2024-09-28', count: 4 },
    { date: '2024-09-29', count: 6 },
    { date: '2024-09-30', count: 8 },
  ],
  viewsByVideo: [
    { name: 'Video 1', views: 12300 },
    { name: 'Video 2', views: 45200 },
    { name: 'Video 3', views: 8900 },
    { name: 'Video 4', views: 15600 },
    { name: 'Video 5', views: 89200 },
  ]
}
